#config location
#~/new_dotfiles/mpd/.config/mpd/mpd.config

#default directory is XDG directory
music directory "/home/admni/Music/wavs"
#playlist directory
playlist_directory "/home/admni/Music/"

auto_update "yes"
bind_to_address "127.0.0.1"
restore_paused "yes" #startup cfg
max_output_buffer_size "16384"


audio_output {
  type "fifo"
  name "Visualiser feed"
  path "/tmp/mpd.fifo"
  format "44100:16:2"
}


