#!/usr/bin/nft -f

destroy table inet filter
table inet filter {
  chain input {
    type filter hook input priority filter
    policy drop
    iif virbr0 accept comment "allow virtual bridge for vm"

    ct state invalid drop          comment "drop invalid connections"
    ct state {established,related} accept comment "allow tracked connections"
    iif lo accept                  comment "allow loopback"
    meta l4proto {icmp,icmpv6} accept comment "allow icmp"
    pkttype host limit rate 5/second counter reject with icmpx type admin-prohibited
    counter
  }

  chain forward {
    type filter hook forward priority filter
    policy accept
    # Docker manages its own forward rules via iptables-nft
  }

  chain output {
    type filter hook output priority filter
    policy accept
  }
}
